Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
Reading Node Data from Serial Port
Could not read data from serial port <class 'serial.serialutil.SerialException'>
^CTraceback (most recent call last):
  File "./N2_Update_BIOT_Base_v07.py", line 55, in <module>
    record = serialPort.readline()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 460, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected?)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./N2_Update_BIOT_Base_v07.py", line 58, in <module>
    time.sleep(5)
KeyboardInterrupt
